spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/serverdb
    username: postgres
    password: password
    pool-size: 30

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
    show-sql: true
